- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Protect the Heads from the fate of death!"
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hours
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlue
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: ERTSecurityPDA
    ears: ClothingHeadsetCentCom
    belt: ClothingBeltSheathFilled
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: DeathAcidifierImplanter
  innerClothingSkirt: ClothingUniformJumpskirtColorBlue
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
