- type: job
  id: NanotrasenRepresentative
  name: Nanotrasen Representative
  description: "Represent NT, Send reports back to them on the stations' situation, Inform the heads of anything CentCom orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: PointLight
        enabled: true
        radius: 1.5
        energy: 2
        color: "#32CD32"

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAgent
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCentcomcap
    eyes: ClothingEyesGlasses
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderCentComClipboard
    pocket1: RubberStampCentcom
    pocket2: WeaponDisabler
  innerClothingSkirt: ClothingUniformJumpskirtDetectiveGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
