# goob edit (full file)
# used for tags and other identification related stuff
# if you see any of these as parents this means the prototype is good edited
# regards

- type: entity
  abstract: true
  id: BaseOrgan
  components:
  - type: Tag
    tags:
    - Organ

- type: entity
  abstract: true
  id: BaseStomach
  components:
  - type: Tag
    tags:
    - Stomach

- type: entity
  abstract: true
  id: BaseLungs
  components:
  - type: Tag
    tags:
    - Lungs

- type: entity
  abstract: true
  id: BaseHeart
  components:
  - type: Tag
    tags:
    - Heart

- type: entity
  abstract: true
  id: BaseLiver
  components:
  - type: Tag
    tags:
    - Liver

- type: entity
  abstract: true
  id: BaseKidneys
  components:
  - type: Tag
    tags:
    - Kidneys

- type: entity
  abstract: true
  id: BaseEyes
  components:
  - type: Tag
    tags:
    - Eyes

- type: entity
  abstract: true
  id: BaseTongue
  components:
  - type: Tag
    tags:
    - Tongue
