name: Reset Git Headers

on:
  workflow_dispatch:

jobs:
  reset-headers:
    runs-on: self-hosted

    steps:
      - name: Check environment variables (before)
        run: env | grep -i authorization || true

      - name: Unset GIT_HTTP_EXTRAHEADER
        run: |
          git config --global --unset-all http.extraheader || true
          unset GIT_HTTP_EXTRAHEADER
          echo "GIT_HTTP_EXTRAHEADER=" >> $GITHUB_ENV

      - name: Check environment variables (after)
        run: env | grep -i authorization || true

      - name: Test Git command
        run: git fetch origin
