name: Update PR Branches

on:
  workflow_dispatch:

jobs:
  update-prs:
    runs-on: self-hosted
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - name: Install GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt update && sudo apt install gh -y
          fi

      - name: Get open pull requests
        id: get-prs
        run: |
          prs=$(GH_TOKEN=${{ secrets.BOT_TOKEN }} gh pr list --state open --json number,headRefName,headRepositoryOwner --jq 'map("\(.number):\(.headRefName):\(.headRepositoryOwner.login)") | @sh' | tr -d "'")
          echo "prs=$prs" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Merge master into each PR branch
        if: env.prs != ''
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Configure submodule handling
          git config --global submodule.recurse true
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GITHUB_TOKEN }} | base64)"

          # Main processing loop
          for pr in $prs; do
            pr_number=$(echo $pr | cut -d':' -f1)
            branch=$(echo $pr | cut -d':' -f2)
            repo_owner=$(echo $pr | cut -d':' -f3)
            origin_repo=$(basename -s .git $(git remote get-url origin))

            # Clean working state
            git reset --hard
            git clean -ffdx
            git checkout master
            git submodule foreach --recursive 'git reset --hard && git clean -ffdx'

            if [ "$repo_owner" != "$(git remote get-url origin | cut -d':' -f2 | cut -d'/' -f1)" ]; then
              fork_remote="fork-$repo_owner"
              fork_repo="https://github.com/$repo_owner/$origin_repo.git"

              # Configure remote
              git remote remove "$fork_remote" || true
              git remote add "$fork_remote" "$fork_repo"
              git fetch "$fork_remote"

              # Verify branch exists
              if ! git ls-remote --exit-code --heads "$fork_remote" "$branch" >/dev/null 2>&1; then
                echo "Branch $branch not found in $fork_remote, skipping PR #$pr_number"
                continue
              fi

              # Checkout branch
              git checkout -B "temp-$branch" "$fork_remote/$branch"
              
              # Update submodules with retries
              for i in 1 2 3; do
                git submodule sync --recursive
                if git submodule update --init --recursive --force --checkout; then
                  break
                fi
                echo "Submodule update failed (attempt $i/3), retrying..."
                sleep 5
              done

              # Merge and push
              if git merge --no-commit origin/master; then
                git commit -m "Merge master into $branch"
                git push "$fork_remote" "temp-$branch:$branch"
              else
                echo "Merge conflict in PR #$pr_number, aborting..."
                git merge --abort || true
              fi

              # Cleanup
              git checkout master
              git branch -D "temp-$branch"
              git remote remove "$fork_remote"

            else
              # Handle same-repo PR
              git fetch origin "$branch"
              git checkout "$branch"
              
              # Update submodules
              git submodule sync --recursive
              git submodule update --init --recursive --force --checkout || true

              if git merge --no-commit origin/master; then
                git commit -m "Merge master into $branch"
                git push origin "$branch"
              else
                echo "Merge conflict in PR #$pr_number, aborting..."
                git merge --abort || true
                git checkout master
              fi
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
