name: Update PR Branches

on:
  workflow_dispatch:

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: update all prs
          uses: maxkomarychev/pr-updater-action@v1.0.0
          with:
                token: ${{ secrets.BOT_TOKEN }}
